players = 2
initial_life = 20

[[libraries]]
player = 1

  [[libraries.cards]]
  name = "Abattoir Ghoul"

  [[libraries.cards]]
  name = "Forest"

  [[libraries.cards]]
  name = "Angelic Overseer"

[[libraries]]
player = 2

  [[libraries.cards]]
  name = "Laboratory Maniac"

  [[libraries.cards]]
  name = "Island"

  [[libraries.cards]]
  name = "Midnight Haunting"
